import Profile from "../models/Profile.js";

export const submitVerification = async (req, res) => {
  try {
    const { profileId, aadharStorageId, panStorageId } = req.body;

    if (!profileId || !aadharStorageId || !panStorageId) {
      return res.status(400).json({
        success: false,
        message: "Required verification documents are missing.",
      });
    }

    const profile = await Profile.findByIdAndUpdate(
      profileId,
      {
        verificationStatus: "pending",
        aadharStorageId,
        panStorageId,

        // Actual URLs will be generated by Cloudinary/storage layer.
        aadharUrl: req.body.aadharUrl,
        panUrl: req.body.panUrl,
      },
      {
        new: true,
        runValidators: true,
      }
    );

    if (!profile) {
      return res.status(404).json({
        success: false,
        message: "Profile not found.",
      });
    }

    res.status(200).json({
      success: true,
      data: profile,
    });
  } catch (error) {
    console.error("Submit verification error:", error);

    res.status(500).json({
      success: false,
      message: "Failed to submit verification.",
    });
  }
};

export const submitBrandVerification = async (req, res) => {
  try {
    const {
      profileId,
      gstNumber,
      gstCertificateStorageId,
    } = req.body;

    if (!profileId || !gstNumber || !gstCertificateStorageId) {
      return res.status(400).json({
        success: false,
        message: "Required GST verification fields are missing.",
      });
    }

    const profile = await Profile.findByIdAndUpdate(
      profileId,
      {
        verificationStatus: "pending",
        gstNumber,
        gstCertificateStorageId,
        gstCertificateUrl: req.body.gstCertificateUrl,
      },
      {
        new: true,
        runValidators: true,
      }
    );

    if (!profile) {
      return res.status(404).json({
        success: false,
        message: "Profile not found.",
      });
    }

    res.status(200).json({
      success: true,
      data: profile,
    });
  } catch (error) {
    console.error("Brand verification error:", error);

    res.status(500).json({
      success: false,
      message: "Failed to submit brand verification.",
    });
  }
};