import Profile from "../models/Profile.js";

export const submitVerification = async (req, res) => {
  try {
    const { profileId, aadharStorageId, panStorageId } = req.body;

    if (!profileId || !aadharStorageId || !panStorageId) {
      return res.status(400).json({
        success: false,
        message: "Required verification documents are missing.",
      });
    }

    const creatorProfile = await Profile.findById(profileId);
    if (!creatorProfile) {
      return res.status(404).json({
        success: false,
        message: "Profile not found.",
      });
    }

    const missingFields = [];
    if (!creatorProfile.handle) missingFields.push("Handle / Username");
    if (!creatorProfile.category) missingFields.push("Category");
    if (!creatorProfile.phone) missingFields.push("Phone");
    if (!creatorProfile.location) missingFields.push("Location");
    if (!creatorProfile.bio) missingFields.push("Bio");
    if (!creatorProfile.startingPrice) missingFields.push("Starting Price");

    if (missingFields.length > 0) {
      return res.status(400).json({
        success: false,
        message: `Missing required information for verification: ${missingFields.join(", ")}`,
      });
    }

    const profile = await Profile.findByIdAndUpdate(
      profileId,
      {
        verificationStatus: "pending",
        aadharStorageId,
        panStorageId,

        // Actual URLs will be generated by Cloudinary/storage layer.
        aadharUrl: req.body.aadharUrl,
        panUrl: req.body.panUrl,
      },
      {
        new: true,
        runValidators: true,
      }
    );

    if (!profile) {
      return res.status(404).json({
        success: false,
        message: "Profile not found.",
      });
    }

    res.status(200).json({
      success: true,
      data: profile,
    });
  } catch (error) {
    console.error("Submit verification error:", error);

    res.status(500).json({
      success: false,
      message: "Failed to submit verification.",
    });
  }
};

export const submitBrandVerification = async (req, res) => {
  try {
    const {
      profileId,
      gstNumber,
      gstCertificateStorageId,
    } = req.body;

    if (!profileId || !gstNumber || !gstCertificateStorageId) {
      return res.status(400).json({
        success: false,
        message: "Required GST verification fields are missing.",
      });
    }

    const brandProfile = await Profile.findById(profileId);
    if (!brandProfile) {
      return res.status(404).json({
        success: false,
        message: "Profile not found.",
      });
    }

    const missingFields = [];
    if (!brandProfile.handle) missingFields.push("Handle / Username");
    if (!brandProfile.category) missingFields.push("Category");
    if (!brandProfile.website) missingFields.push("Website");
    if (!brandProfile.location) missingFields.push("Location");
    if (!brandProfile.companySize) missingFields.push("Company Size");

    if (missingFields.length > 0) {
      return res.status(400).json({
        success: false,
        message: `Missing required information for verification: ${missingFields.join(", ")}`,
      });
    }

    const profile = await Profile.findByIdAndUpdate(
      profileId,
      {
        verificationStatus: "pending",
        gstNumber,
        gstCertificateStorageId,
        gstCertificateUrl: req.body.gstCertificateUrl,
      },
      {
        new: true,
        runValidators: true,
      }
    );

    if (!profile) {
      return res.status(404).json({
        success: false,
        message: "Profile not found.",
      });
    }

    res.status(200).json({
      success: true,
      data: profile,
    });
  } catch (error) {
    console.error("Brand verification error:", error);

    res.status(500).json({
      success: false,
      message: "Failed to submit brand verification.",
    });
  }
};